[package]
name = "rust_web_frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19.3"
stylist = { version = "0.10.0", features = ["yew"]}
# gloo = "0.6.1"
# wasm-bindgen = "0.2.79"
# web-sys = { version = "0.3.56", features = ["HtmlInputElement"] }
